name: deploy

on:
  push:
    branches:
      - main  # Reemplaza "main" con el nombre de tu rama principal

jobs:
  despliegue:
    runs-on: windows-10-Pro  # Indica la imagen de sistema operativo en la que se ejecutará el flujo de trabajo

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2  # Utiliza una acción predefinida para realizar el checkout del código desde el repositorio

    - name: Configurar Python
      uses: actions/setup-python@v2  # Utiliza una acción predefinida para configurar Python en el entorno de ejecución

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Instala las dependencias de tu proyecto desde requirements.txt

    - name: Desplegar con Waitress
      run: |
        python manage.py migrate  # Ejemplo: ejecuta las migraciones de Django si es necesario
        python servidor.py  # Despliega tu aplicación con Waitress
