# Generated by Django 5.0.1 on 2024-01-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Nombre de Usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre')),
                ('apellidos', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellidos')),
                ('area', models.CharField(choices=[('Área', 'Área'), ('CALIDAD', 'CALIDAD'), ('CENTROS MÉDICOS', 'CENTROS MÉDICOS'), ('DOCTORES CENTROS MÉDICOS', 'DOCTORES CENTROS MÉDICOS'), ('ESTERILIZACIÓN', 'ESTERILIZACIÓN'), ('GERENCIA ADMINISTRACIÓN', 'GERENCIA ADMINISTRACIÓN'), ('GERENCIA GENERAL', 'GERENCIA GENERAL'), ('GERENCIA FINANZAS', 'GERENCIA FINANZAS'), ('GERENCIA AMBULATORIA', 'GERENCIA AMBULATORIA'), ('GERENCIA DE SALUD', 'GERENCIA DE SALUD'), ('GERENCIA COMERCIAL', 'GERENCIA COMERCIAL'), ('LABORATORIO', 'LABORATORIO'), ('MATERNIDAD/NEO', 'MATERNIDAD/NEO'), ('PABELLÓN', 'PABELLÓN'), ('UNIDAD DE EXAMENES', 'UNIDAD DE EXAMENES'), ('UNIDAD HOSPITALIZACIÓN', 'UNIDAD HOSPITALIZACIÓN'), ('UTI', 'UTI'), ('URGENCIA/RECEPCIÓN DE URGENCIAS', 'URGENCIA/RECEPCIÓN DE URGENCIAS'), ('OTRAS UNIDADES', 'OTRAS UNIDADES')], default='Área', max_length=100, null=True, verbose_name='Área')),
                ('telefono', models.CharField(blank=True, max_length=13, null=True, verbose_name='Teléfono')),
                ('hipo', models.BooleanField(default=False)),
                ('diario', models.BooleanField(default=False)),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
