# Generated by Django 5.0.1 on 2024-01-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipo',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(default='', max_length=15, verbose_name='IP Equipo')),
                ('tipo', models.CharField(choices=[('Tipo de Equipo', 'Tipo de Equipo'), ('COMPUTADOR', 'COMPUTADOR'), ('IMPRESORA', 'IMPRESORA')], default='Tipo de Equipo', max_length=30, verbose_name='Tipo de Equipo')),
                ('ubicacion', models.CharField(default='', max_length=50, verbose_name='Ubicación de Equipo')),
                ('mac', models.CharField(default='', max_length=20, verbose_name='MAC Equipo')),
                ('mantencion', models.DateField(verbose_name=['%d%m/%Y'])),
                ('estadoMant', models.CharField(default='PENDIENTE', max_length=12, verbose_name='Estado Mantención')),
            ],
        ),
    ]
