# Generated by Django 5.0.1 on 2024-01-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='estadoMant',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('REALIZADA', 'REALIZADA')], default='PENDIENTE', max_length=12, verbose_name='Estado Mantención'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='mantencion',
            field=models.DateField(verbose_name=['%d/%m/%Y']),
        ),
    ]
