# Generated by Django 5.0.1 on 2024-01-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0004_alter_equipo_ip_alter_equipo_mac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='mantencion',
            field=models.CharField(default='Sin Fecha', max_length=20, verbose_name='Fecha Mantención'),
        ),
    ]
