# Generated by Django 5.0.1 on 2024-01-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0006_alter_equipo_mantencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='modelo',
            field=models.CharField(default='', max_length=50, verbose_name='Modelo de Equipo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(default='', max_length=30, verbose_name='Nombre de Equipo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='proce',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Procesador'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='ram',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='RAM'),
        ),
    ]
