# Generated by Django 5.0.1 on 2024-02-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0007_equipo_modelo_equipo_nombre_equipo_proce_equipo_ram'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='disco',
            field=models.CharField(blank=True, default='-', max_length=5, verbose_name='Disco'),
        ),
    ]
