# Generated by Django 5.0.1 on 2024-02-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0008_equipo_disco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='disco',
            field=models.CharField(blank=True, choices=[('-', '-'), ('SSD', 'SSD'), ('HDD', 'HDD')], default='-', max_length=5, verbose_name='Disco'),
        ),
    ]
