# Generated by Django 4.2.6 on 2024-02-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0011_remove_equipo_estadomant'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='required',
            field=models.BooleanField(default=False, verbose_name='Requiere Mantención'),
        ),
    ]
