# Generated by Django 4.2.6 on 2024-02-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0013_equipo_licencia_equipo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='proce',
            field=models.CharField(blank=True, default='-', max_length=40, verbose_name='Procesador'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='ram',
            field=models.CharField(blank=True, default='-', max_length=15, verbose_name='RAM'),
        ),
    ]
